Add devcontianer settings
ShotaAk/max_e1_apps pull request #1
Opened 2021-07-02 02:48 UTC by meganetaaan

Added devcontainer settings for VSCode

* C++ preset
* clone and build [Dynamixel SDK](https://github.com/ROBOTIS-GIT/DynamixelSDK) at `/external` directory

2021-07-05 02:02 UTC, ShotaAk requested changes
Thank you for your contribution!
Please check my comments.

2021-07-05 02:02 UTC, ShotaAk commented on .devcontainer/Dockerfile
> +ARG VARIANT="buster"
Could you please change this to `ubuntu 20.04`?
The uninstall script didn't work properly on debian-10. It's probably due to a different version of cmake.

2021-07-05 02:02 UTC, ShotaAk commented on .devcontainer/devcontainer.json
> +		"args": { "VARIANT": "debian-10" }
Could you please change this to `ubuntu 20.04`?

2021-07-05 02:02 UTC, ShotaAk commented on build_install.bash
> -#!/usr/bin/bash -e
Please remove this change after switching the environment to `ubuntu 20.04`.

2021-07-05 02:02 UTC, ShotaAk commented on max_e1_examples/CMakeLists.txt
> +
Thanks!

2021-07-06 01:46 UTC, meganetaaan commented on .devcontainer/Dockerfile
> +ARG VARIANT="buster"
Fixed to Ubuntu 20.04 and confirmed that it works.

2021-07-06 01:47 UTC, meganetaaan commented on .devcontainer/devcontainer.json
> +		"args": { "VARIANT": "debian-10" }
Fixed.

2021-07-06 01:47 UTC, meganetaaan commented on build_install.bash
> -#!/usr/bin/bash -e
Fixed.

2021-07-06 01:51 UTC, meganetaaan commented
All requested changes have been fixed. Please confirm them.

2021-07-19 01:44 UTC, ShotaAk approved these changes
LGTM

2021-07-19 01:44 UTC, merged